# Generated manually to establish domain tables for the FHIR portal sample services.
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HL7BatchRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_id", models.CharField(max_length=64, unique=True)),
                ("total_messages", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("processing_time", models.CharField(blank=True, max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="HL7Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_id", models.CharField(max_length=64, unique=True)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("raw_message", models.TextField()),
                ("fhir_resources", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_id", models.CharField(max_length=64, unique=True)),
                ("identifier", models.CharField(blank=True, max_length=128)),
                ("name", models.CharField(blank=True, max_length=256)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="PatientMergeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_patient_id", models.CharField(max_length=64)),
                ("target_patient_id", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("merge_strategy", models.CharField(blank=True, max_length=64)),
                ("merged_fields", models.JSONField(blank=True, default=list)),
                ("audit_reason", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PatientExportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("export_id", models.CharField(max_length=64, unique=True)),
                ("patient_id", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("format", models.CharField(max_length=16)),
                ("include_sections", models.JSONField(blank=True, default=list)),
                ("download_url", models.CharField(blank=True, max_length=512)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ObservationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observation_id", models.CharField(max_length=64, unique=True)),
                ("patient_reference", models.CharField(blank=True, max_length=128)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("code", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("effective_datetime", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ObservationAlertConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_id", models.CharField(max_length=64)),
                ("observation_code", models.CharField(max_length=64)),
                ("thresholds", models.JSONField(blank=True, default=dict)),
                ("notification_channels", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"unique_together": {("patient_id", "observation_code")}},
        ),
        migrations.CreateModel(
            name="AppointmentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment_id", models.CharField(max_length=64, unique=True)),
                ("status", models.CharField(max_length=32)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("patient_reference", models.CharField(blank=True, max_length=128)),
                ("practitioner_reference", models.CharField(blank=True, max_length=128)),
                ("service_category", models.CharField(blank=True, max_length=128)),
                ("appointment_type", models.CharField(blank=True, max_length=128)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment_id", models.CharField(max_length=64)),
                ("patient_id", models.CharField(max_length=64)),
                ("preferred_dates", models.JSONField(blank=True, default=list)),
                ("preferred_times", models.JSONField(blank=True, default=list)),
                ("priority", models.CharField(blank=True, max_length=32)),
                ("notification_preferences", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AuthEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=32)),
                ("username", models.CharField(blank=True, max_length=256)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="RoleAssignmentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignment_id", models.CharField(max_length=64, unique=True)),
                ("user_id", models.CharField(max_length=64)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("effective_date", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="AbacEvaluationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=64)),
                ("resource_type", models.CharField(max_length=64)),
                ("resource_id", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=32)),
                ("decision", models.CharField(max_length=32)),
                ("context", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="TelemedicineSessionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("appointment_id", models.CharField(blank=True, max_length=64)),
                ("session_type", models.CharField(blank=True, max_length=64)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("estimated_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("join_urls", models.JSONField(blank=True, default=dict)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="TelemedicineConsentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(max_length=64)),
                ("user_id", models.CharField(max_length=64)),
                ("consent_type", models.CharField(max_length=64)),
                ("granted", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
            ],
            options={"unique_together": {("session_id", "user_id", "consent_type")}},
        ),
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notification_id", models.CharField(max_length=64, unique=True)),
                ("recipient_id", models.CharField(max_length=64)),
                ("template", models.CharField(blank=True, max_length=128)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("channels", models.JSONField(blank=True, default=dict)),
                ("variables", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_name", models.CharField(max_length=128)),
                ("template_name", models.CharField(max_length=128)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("recipients", models.JSONField(blank=True, default=list)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsRiskScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_id", models.CharField(max_length=64)),
                ("risk_type", models.CharField(max_length=64)),
                ("score", models.FloatField(default=0)),
                ("level", models.CharField(blank=True, max_length=32)),
                ("confidence", models.FloatField(default=0)),
                ("factors", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
            ],
            options={"unique_together": {("patient_id", "risk_type")}},
        ),
        migrations.CreateModel(
            name="AnalyticsTrainingJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("training_job_id", models.CharField(max_length=64, unique=True)),
                ("model_name", models.CharField(max_length=128)),
                ("model_type", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("progress", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsAlertConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alert_id", models.CharField(max_length=64, unique=True)),
                ("patient_id", models.CharField(max_length=64)),
                ("model_id", models.CharField(max_length=64)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("assessment", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsTrendRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analysis_id", models.CharField(max_length=64, unique=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("trends", models.JSONField(blank=True, default=list)),
                ("correlations", models.JSONField(blank=True, default=list)),
                ("anomalies", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsFhirLinkRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linking_id", models.CharField(max_length=64, unique=True)),
                ("patient_id", models.CharField(max_length=64)),
                ("model_id", models.CharField(max_length=64)),
                ("fhir_resources", models.JSONField(blank=True, default=list)),
                ("audit_trail", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEventRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_id", models.CharField(max_length=64, unique=True)),
                ("event_type", models.CharField(max_length=64)),
                ("user_id", models.CharField(max_length=64)),
                ("resource_type", models.CharField(max_length=64)),
                ("resource_id", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=32)),
                ("timestamp_value", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AuditExportRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("export_id", models.CharField(max_length=64, unique=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(max_length=32)),
                ("download_url", models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="AuditAnomalyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anomaly_id", models.CharField(max_length=64, unique=True)),
                ("user_id", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("severity", models.CharField(blank=True, max_length=32)),
                ("score", models.FloatField(default=0)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="FhirGatewayRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_id", models.CharField(max_length=64, unique=True)),
                ("resource_type", models.CharField(max_length=64)),
                ("resource_id", models.CharField(blank=True, max_length=64)),
                ("method", models.CharField(max_length=16)),
                ("status_code", models.PositiveIntegerField(default=200)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="KafkaTopicConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="KafkaEventRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("event_type", models.CharField(max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="KafkaDeadLetterRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dlq_event_id", models.CharField(max_length=64, unique=True)),
                ("original_event", models.JSONField(blank=True, default=dict)),
                ("failure_info", models.JSONField(blank=True, default=dict)),
                ("routing", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
